"use client";
import { DndContext, DragEndEvent, DragOverlay, PointerSensor, useDraggable, useSensor, useSensors } from "@dnd-kit/core";
import { useState } from "react";
import { DailyTimeline } from "@/components/planner/DailyTimeline";
import { formatLocalDate } from "@/lib/date/local-date";
import { validatePlacement, type ScheduledTask } from "@/lib/scheduling/placement";
import { getTasksForDate, type TodaysTask } from "@/lib/tasks/task-selector";
import { loadScheduledTasks, saveScheduledTasks } from "@/data/repositories/schedule-repository";
import type { FixedSchedule, TaskAssignment, TaskTemplate } from "@/types/domain";
function Draggable({ task }: { task: TodaysTask }) { const { attributes, listeners, setNodeRef } = useDraggable({ id: task.dailyTaskId, data: { task } }); return <article ref={setNodeRef} {...attributes} {...listeners} className="rounded-2xl border border-[#d9c9ec] bg-[#f4effb] p-4 shadow-sm touch-none cursor-grab active:cursor-grabbing"><b>{task.icon} {task.name}</b><p className="mt-1 text-sm">🕒 {task.durationMinutes} min · ⭐ {task.points}</p></article>; }
export function SchedulingBoard({ date, childId, schedules, templates, assignments }: { date: Date; childId: string; schedules: FixedSchedule[]; templates: TaskTemplate[]; assignments: TaskAssignment[] }) { const key = formatLocalDate(date); const all = getTasksForDate(childId, date, templates, assignments); const [planned, setPlanned] = useState<ScheduledTask[]>(() => loadScheduledTasks(childId, key)); const [active, setActive] = useState<TodaysTask | null>(null); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } })); const commit = (next: ScheduledTask[]) => { setPlanned(next); saveScheduledTasks(childId, key, next); }; const onEnd = (event: DragEndEvent) => { const task = event.active.data.current?.task as TodaysTask | undefined; if (!task || event.over?.id !== "timeline") return; const top = event.active.rect.current.translated?.top ?? 0; const laneTop = event.over.rect.top; const start = 360 + Math.round((top - laneTop) / 1.1 / 5) * 5; const result = validatePlacement({ startMinutes: start, durationMinutes: task.durationMinutes, fixedSchedules: schedules, scheduledTasks: planned }); if (result.valid) commit([...planned, { id: task.dailyTaskId, dailyTaskId: task.dailyTaskId, taskTemplateId: task.id, startMinutes: start, durationMinutes: task.durationMinutes }]); setActive(null); }; const remaining = all.filter((task) => !planned.some((item) => item.dailyTaskId === task.dailyTaskId)); return <DndContext sensors={sensors} onDragStart={(event) => setActive(event.active.data.current?.task as TodaysTask)} onDragEnd={onEnd} onDragCancel={() => setActive(null)}><div className="grid gap-6 lg:grid-cols-[minmax(0,1.7fr)_minmax(290px,.9fr)]"><DailyTimeline schedules={schedules} scheduledTasks={planned} templates={templates} /><aside className="rounded-[28px] border border-[#f0dfcd] bg-[#fffaf3] p-5"><h2 className="text-2xl font-extrabold">Today&apos;s Tasks 🌟</h2><p className="mt-2 text-sm">{remaining.length ? `${remaining.length} left to plan` : "🎉 All planned!"}</p><div className="mt-5 space-y-3">{remaining.map((task) => <Draggable key={task.dailyTaskId} task={task} />)}</div></aside></div><DragOverlay>{active ? <div className="rounded-2xl bg-white p-3 shadow-xl">{active.icon} {active.name} · {active.durationMinutes} min</div> : null}</DragOverlay></DndContext>; }
